//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public decimal FNSTUDENTID { get; set; }
        public string FCSTUDCODE { get; set; }
        public string FCSTUDTYPE { get; set; }
        public string FCLASTNAME { get; set; }
        public string FCFIRSTNAME { get; set; }
        public string FCMIDNAME { get; set; }
        public string FCSEX { get; set; }
        public decimal FNPROGRAMID { get; set; }
        public decimal FNBATCHYEAR { get; set; }
        public Nullable<decimal> FNSPCLID { get; set; }
        public string FCNICKNAME { get; set; }
        public string FCCITIZENSHIP { get; set; }
        public string FCCIVILSTATUS { get; set; }
        public string FCBEGSTATUS { get; set; }
        public string FCACADSTATUS { get; set; }
        public Nullable<System.DateTime> FDBIRTHDATE { get; set; }
        public string FCBIRTHPLACE { get; set; }
        public string FCRELIGION { get; set; }
        public string FCLANGUAGES { get; set; }
        public string FCRSTREET { get; set; }
        public string FCRDISTRICT { get; set; }
        public string FCRTOWN { get; set; }
        public string FCMSTREET { get; set; }
        public string FCMDISTRICT { get; set; }
        public string FCMTOWN { get; set; }
        public string FCTELEPHONE { get; set; }
        public string FCHSATTENDED { get; set; }
        public string FCLASTUSER { get; set; }
        public Nullable<System.DateTime> FDLASTUPDATE { get; set; }
        public string FCPIN { get; set; }
        public string FCPRNTPIN { get; set; }
        public string FCACTVCODE { get; set; }
        public Nullable<decimal> FNENTRYYEAR { get; set; }
        public string FCCATEGORY { get; set; }
        public string FCEMAIL { get; set; }
        public Nullable<int> fncurrentyear { get; set; }
        public string fcCurriculumID { get; set; }
        public Nullable<decimal> fnStudTypeID { get; set; }
        public Nullable<decimal> fnCategoryID { get; set; }
        public Nullable<int> FNAPPLICANTID { get; set; }
    }
}
